[package]
name = "c3"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
serde = "1.0.215"
time = { version = "0.3", features = ["formatting"] }
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.11.0", features = ["v4"] }
