[package]
name = "c3"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
log = "0.4.22"
serde = "1.0.215"
time = { version = "0.3", features = ["formatting"] }
tokio = "1.41.1"
uuid = "1.11.0"
